version: '3.6'

networks:
  taxes_network:
    driver: bridge

services:
  webui:
    image: taxes_api
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    environment:
      - "ConnectionStrings:DefaultConnection=Host=postgres;Database=taxes_db;Username=taxes;Password=changeme;port=5432;"
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - postgres
    networks:
      - taxes_network      
    restart: on-failure
    volumes:
      - ~/.aspnet/https:/https:ro

  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: taxes
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres1
    volumes:
      - postgres:/data/postgres1
    ports:
      - "5432:5432"
    networks:
      - taxes_network
    restart: unless-stopped


volumes:
  postgres:    